### ISSUE TITLE
How to compile findpar5.hs?

### ISSUE THREAD

**Issue by isaiah** [simonmar/parconc-examples#14]
The problem is with the following code:

```haskell
liftPar :: ParIO a -> EParIO a
liftPar p = E $ p >>= return . Right

new :: EParIO (EVar a)
new = liftPar P.new
-- new :: Par (IVar a) 
```

`Par.new` returns a `Par (IVar a)` not `ParIO (IVar a)`, how can I get this compiling? I have the same problem getting the code in the book working.

GHC 7.10.3, cabal 1.22.5.0

**Comment by isaiah** [comment]
I figured out that I could use `unsafeCoerce` to coerce between the two, just in case anyone encounters the same problem.

```haskell
-- import Unsafe.Coerce
new :: EParIO (EVar a)
new = liftPar $ unsafeCoerce P.new
```

was this handled by `GeneralizedNewtypeDeriving` extension before?

**Comment by simonmar** [comment]
I just pushed changes to make `findpar5.hs` compile, and uploaded 0.4.1 to Hackage.
