### ISSUE TITLE
git clone on Mac

### ISSUE THREAD

**Issue by steshaw** [simonmar/parconc-examples#15]
Cloning this repository on Mac with a case-insensitive filesystem doesn't work because of the files TMVar.hs and tmvar.hs (one of which is a soft-link to the other).

I propose to put these "miscmodules" into a subdirectory with soft links back to the parent directory. This way the filenames are still the same as in the book but the code can be used on a Mac with the default filesystem.

**Comment by steshaw** [comment]
I submitted PR #16.

**Comment by FranklinChen** [comment]
This appears fixed now, so can be closed.

**Comment by simonmar** [comment]
Thanks!
