### ISSUE TITLE
fails to install on ghc 8.4.3 - Could not resolve dependencies

### ISSUE THREAD

**Issue by GeorgeCo** [simonmar/parconc-examples#25]
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.3
 cabal install --only-dependencies
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: parconc-examples-0.4.5 (user goal)
[__1] next goal: base (dependency of parconc-examples)
[__1] rejecting: base-4.11.1.0/installed-4.1... (conflict: parconc-examples =>
base>=4.5 && <4.9)
[__1] rejecting: base-4.11.1.0, base-4.11.0.0, base-4.10.1.0, base-4.10.0.0,
base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0,
base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0,
base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0,
base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0,
base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable
package requires installed instance)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, parconc-examples

It succeeds if I add --allow-new

**Comment by simonmar** [comment]
Fixed!
